# Generated by Django 4.2.1 on 2023-05-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='participantes',
            new_name='integrantes',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='professor_responsavel',
            new_name='responsavel',
        ),
    ]
